spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  #MyBatis 설정
mybatis:
  type-aliases-package: keepgoing.demo.domain.diet.entity, keepgoing.demo.domain.member.entity, keepgoing.demo.domain.ai.entity
  mapper-locations: classpath:/mappers/**/*.xml
  configuration.map-underscore-to-camel-case: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: ${GOOGLE_REDIRECT_URI}
#            scope:
#              - email
#              - profile
