# application-dev.yml
# ==================================
# dev 프로파일에서만 사용될 민감 정보
# ==================================

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepgoing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234